name: CD

on:
  push:
    branches: ["main"]

env:
  GCP_CONTAINER_REPO: "asylumtix-admin-platform"

  IMAGE_NAME: "asylumtix-admin-platform-web"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - name: "Set up Google Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: "Configure Docker"
        run: "gcloud configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev"

      - name: Build Docker image
        run: docker build . -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ env.GCP_CONTAINER_REPO }}/${{ env.IMAGE_NAME }}

      - name: Push image to Google Container Registry
        run: docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{env.GCP_CONTAINER_REPO}}/${{ env.IMAGE_NAME }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "asylumtix-admin-platform-web"
          image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{env.GCP_CONTAINER_REPO}}/${{ env.IMAGE_NAME }}
          env_vars: ${{ secrets.IMAGE_ENV_VARS }}

      - name: "Service URL"
        run: echo "${{ steps.deploy.outputs.url }}"
